name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: load dependencies
      run: make bin-depth

    - name: lint
      run: make lint

  migrations:
    needs: [build]
    steps:
      - name: migrate
        run: make db:up

  test:
    needs: [build, migrations]
    steps:
      - name: testing
        run: make test

