name: Main-Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  testing:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: load dependencies
      run: make bin-depth

    - name: lint
      run: make lint

    - name: migrations
      run: make db:up

    - name: testing
      run: make test

